In [20]:
import pandas as pd

In [75]:
df = pd.read_csv('template.csv')

In [76]:
df["length_caption"] = df["caption"].map(lambda x: len(x))

In [77]:
df["tag"] = df["caption"].map(lambda x: x.count('#'))

In [78]:
from datetime import datetime

def date_diff(date):
    date = date[:11]
    date_in_datetime = datetime.strptime(date, " %Y-%m-%d")
    today_in_datetime = datetime.now()
    day_diff_in_datetime = (today_in_datetime - date_in_datetime).days
    return int(day_diff_in_datetime)

In [79]:
df["date_diff"] = df["date"].map(date_diff)

In [81]:
df["mention"] = df["caption"].map(lambda x: x.count("@"))

In [83]:
df["like ration"] = df["good"] / df["follower"]

In [84]:
df.head()

,caption,follower,following,good,comment,date,url,label,length_caption,tag,date_diff,mention,like ration
0,ここは適当なストリング,1000,200,400,12,2021-01-04T06:40:33.000Z,www.sample.com,1,11,0,365,0,0.4
1,random string,500,300,100,4,2020-01-04T06:40:33.000Z,www.hallo.com,0,13,0,731,0,0.2
2,random string #hallo #lol,500,300,100,4,2021-10-04T06:40:33.000Z,www.hallo.com,0,25,2,92,0,0.2
3,random string #hallo #what #where,500,300,100,4,2021-03-23T06:40:33.000Z,www.hallo.com,0,33,3,287,0,0.2
4,random string,500,300,100,4,2021-02-04T06:40:33.000Z,www.hallo.com,0,13,0,334,0,0.2

In [86]:
df[["label", "length_caption", "tag", "date_diff", "mention", "like ration", "follower", "following"]]

,label,length_caption,tag,date_diff,mention,like ration,follower,following
0,1,11,0,365,0,0.4,1000,200
1,0,13,0,731,0,0.2,500,300
2,0,25,2,92,0,0.2,500,300
3,0,33,3,287,0,0.2,500,300
4,0,13,0,334,0,0.2,500,300
5,0,13,0,257,0,0.2,500,300
6,0,13,0,235,0,0.2,500,300
7,0,13,0,0,0,0.2,500,300
8,0,13,0,0,0,0.2,500,300
9,0,13,0,0,0,0.2,500,300
10,0,13,0,0,0,0.2,500,300
11,0,13,0,0,0,0.2,500,300
12,0,13,0,0,0,0.2,500,300
13,0,13,0,0,0,0.2,500,300
14,0,13,0,0,0,0.2,500,300
15,0,13,0,0,0,0.2,500,300
16,0,13,0,0,0,0.2,500,300
17,0,13,0,0,0,0.2,500,300
18,0,13,0,0,0,0.2,500,300